GET_DATA: 
  school_id : "69d62be1-d6bb-4216-b8bf-4372b36f4942"
  local_dir : "data"
  data_file_name : "Raw_data.csv"
  bucket_name : "test_data_bb"
  auth_json_path : "examly-events-26d60ca289a0.json"
  bucket_auth : 'examly-dev-46b364d962d5.json'
  transformed_data_file : "transformed_data.pkl"
  school_codes : ['rmkec496', 'psgtech', 'cbit450', 'psgtech850', 'gprec748',
       'neowise', 'bit410', 'mazenet708', 'neohire', 'placementseason668',
       'neopat', 'neocoder', 'srit508', 'pvpsit551', 'nhce745', 'srec689',
       'gnits963', 'nivrittigurukul', 'kcg168', 'veltech908', 'bphc',
       'kongu229', 'skct892', 'eiphexaware', 'jeppiaar645', 'nandha416',
       'hits606', 'srec694', 'abes819', 'neocoder885', 'vit162',
       'wileynxt679', 'monster439', 'kpriet462', 'kctplacement196',
       'recw641', None, 'virtusacoetraining', 'saranathan468', 'sjec162',
       'skcet530', 'srm615', 'rgukt779', 'talentio627',
       'publicissapient143', 'vemu110', 'trimbletraining', 'mits923',
       'ait338', 'mcet848', 'abctechtraining543', 'vcet972',
       'karpagam885', 'achariya390', 'ksrct438', 'sathyabama250',
       'lpu375', 'futurense299', 'nandha552', 'vnrvjiet858', 'vjit342',
       'srmap483', 'examly188', 'heptagon261', 'svcet702', 'dpk422',
       'cuhimachal132', 'kscollege408', 'sonatech664', 'sixphrase111',
       'rec502', 'hcl147', 'codspiration258', 'jscoe516', 'cupunjab230',
       'hindusthan919', 'srkr378', 'karunya711', 'cmrit977',
       'wileynxt355', 'capgemini913', 'college532', 'rvrjc432', 'svec931',
       'vistas296', 'klu219', 'examly846', 'cmrtc774',
       'rmkinstitutions571', 'vvce364', 'uls450', 'sret176', 'mvsrec738',
       'sastra173', 'mietjmu215', 'virtusacareerfair205', 'vignanits713',
       'bpgcpt', 'ngpit883', 'cmrec487', 'bitspilani', 'bit316',
       'ksrmce305', 'accelya758', 'examly468', 'licet837', 'ssgmce562',
       'gpcet369', 'cmrcet286', 'mcet466', 'vcetp842', 'svpcet934',
       'sitams710', 'rec647', 'jeppiaarsrr998', 'cccdigital704',
       'pstech179', 'vtindia309', 'ngpit663', 'neocolab212', 'altran919',
       'vsb437', 'psgim564', 'vvit123', 'siet826', 'nktech377', 'lti399',
       'psgcas355', 'smartcliff', 'examly827', 'bist854', 'srmap632',
       'msmf836', 'cmrsoet187', 'latentview634', 'kct831', 'kongu426',
       'srit794', 'svce201', 'kct559', 'theem355', 'srm343', 'skct279',
       'sambhram', 'blackboardlearning263', 'neoexam145', 'iiitranchi486',
       'sairam641', 'kclas495', 'hicet902', 'placementseason441',
       'livewire', 'examlycollegedemo768', 'kctsea137', 'lscindia114',
       'suntek444', 'cmrims873', 'gndec602', 'sjcit341', 'lendi459',
       'srcas255', 'kiit721', 'edusaksham424', 'full175',
       'jainuniversity686', 'vcet637', 'sanmar849', 'srit609',
       'francisxavier156', 'kpriet190', 'rmd279', 'grd946',
       'skillcenter132', 'internaltraining', 'sricollege593', 'skasc346',
       'sece949', 'psgias574', 'gallagher462', 'vaels976', 'hit793',
       'vvit740', 'jaipuria473', 'vidal518', 'hicas366',
       'hakunamatata744', 'tce367', 'sitmng142', 'jaihoacademy',
       'zoomrx594', 'skcet956', 'centizen797', 'nxtnewton411', 'tocpt799',
       'spark327', 'futurense904', 'latentviewlnd365', 'mango272',
       'nsda551', 'dsnsystems762', 'trimble931', 'crescent708',
       'pickyourtrail992', 'rmkcet343', 'juet882', 'toce802',
       'examlytrainingdemo599', 'kit291', 'autogram669', 'itrack140',
       'benchmarktraining603', 'dsit654', '18h629', 'techaspect715',
       'slickpos557', 'avcoe605', 'tsinstitute736', 'latentview658',
       'nssce663', 'scsvmv306', 'nasscom', 'universaleducation182',
       'aiet185', 'rmk685', 'sdmcet454', 'svc835', 'jnnce661',
       'examlycompany606', 'skcetplacement393']